services:
  redis:
    image: redis
    ports:
      - 6379:6379
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABSE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysqlvolume:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P $$MYSQLDB_DOCKER_PORT -u root -p$$MYSQL_ROOT_PASSWORD" ]
      timeout: 5s
      retries: 10
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventoryapp
    env_file: .env
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&useTimezone=trues&serverTimeZone=UTC
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    links:
      - redis

volumes:
  mysqlvolume: