scrape_configs:
  - job_name: "inventory-app-api"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 1m # how often to scrape
    static_configs:
      - targets: ["inventory-api-pgb4.onrender.com"]
#      - targets: ["host.docker.internal:8080"] local env